### ISSUE TITLE
Biostar3 Test Coverage

### ISSUE THREAD

**Issue by scgruber** [ialbert/biostar-central#374]
## To-do:
- [ ] `biostar3/charms/views.py`
- [ ] `biostar3/forum/ajax.py`
- [ ] `biostar3/forum/api.py`
- [ ] `biostar3/forum/auth.py`
- [ ] `biostar3/forum/feeds.py`
- [ ] `biostar3/forum/form_views.py`
- [ ] `biostar3/forum/post_views.py`
- [ ] `biostar3/forum/search.py`
- [ ] `biostar3/forum/search_indexes.py`
- [ ] `biostar3/forum/user_views.py`
- [ ] `biostar3/middleware.py`
- [x] `biostar3/utils/flatpage.py`

### Ignoring the following:
- `biostar3/forum/management/commands/` &mdash; just glue for `manage.py`
- `biostar3/forum/migrations/` &mdash; just migrations
- `biostar3/settings/` &mdash; just settings, no logic
- `biostar3/utils/compat.py` &mdash; language features
- `biostar3/utils/email_reply_parser.py` &mdash; external library
- `run/` &mdash; just settings, no logic

**Comment by scgruber** [comment]
Full output from coverage on the current revision:

```
Name                                                     Stmts   Miss  Cover
----------------------------------------------------------------------------
biostar3/__init__                                            3      0   100%
biostar3/celery                                              7      0   100%
biostar3/charms/__init__                                     0      0   100%
biostar3/charms/admin                                        1      0   100%
biostar3/charms/migrations/__init__                          0      0   100%
biostar3/charms/models                                       1      0   100%
biostar3/charms/tests                                        1      0   100%
biostar3/charms/urls                                         5      0   100%
biostar3/charms/views                                       20     12    40%
biostar3/context                                            40      2    95%
biostar3/forum/__init__                                      2      0   100%
biostar3/forum/admin                                        22      0   100%
biostar3/forum/ajax                                        272    193    29%
biostar3/forum/api                                         124     92    26%
biostar3/forum/apps                                         45      3    93%
biostar3/forum/auth                                        135     59    56%
biostar3/forum/awards                                      151      4    97%
biostar3/forum/cache                                        21      0   100%
biostar3/forum/feeds                                       109     53    51%
biostar3/forum/form_views                                  201     99    51%
biostar3/forum/html                                        114     24    79%
biostar3/forum/mailer                                       98     21    79%
biostar3/forum/management/__init__                           1      0   100%
biostar3/forum/management/commands/__init__                  1      1     0%
biostar3/forum/management/commands/add_pages                16     16     0%
biostar3/forum/management/commands/biostar_pg_dump          36     36     0%
biostar3/forum/management/commands/check_email_handler      43     43     0%
biostar3/forum/management/commands/generate_awards          25     25     0%
biostar3/forum/management/commands/generate_sitemap         30     30     0%
biostar3/forum/management/commands/import_phpbb            121    121     0%
biostar3/forum/management/commands/migrate2to3              34     34     0%
biostar3/forum/management/commands/patch                    32     32     0%
biostar3/forum/management/commands/post_convert             31     31     0%
biostar3/forum/management/commands/send_test_email          26     26     0%
biostar3/forum/management/commands/sql_utils                33     33     0%
biostar3/forum/migrations/0001_initial                       7      0   100%
biostar3/forum/migrations/0002_auto_20150625_1755            9      0   100%
biostar3/forum/migrations/0003_auto_20150626_1533            6      0   100%
biostar3/forum/migrations/0004_auto_20150630_1535            5      0   100%
biostar3/forum/migrations/__init__                           0      0   100%
biostar3/forum/models                                      437     72    84%
biostar3/forum/post_views                                  194     72    63%
biostar3/forum/query                                       141     28    80%
biostar3/forum/search                                       31     22    29%
biostar3/forum/search_indexes                               86     31    64%
biostar3/forum/signals                                      44      5    89%
biostar3/forum/tasks                                        60     17    72%
biostar3/forum/templatetags/__init__                         1      0   100%
biostar3/forum/templatetags/widgets                        167     45    73%
biostar3/forum/tests/__init__                                1      0   100%
biostar3/forum/tests/test_client                           156      6    96%
biostar3/forum/tests/test_mailer                            16      0   100%
biostar3/forum/tests/test_moderation                       238      0   100%
biostar3/forum/tests/test_objects                          124      2    98%
biostar3/forum/tests/test_voting                           115      0   100%
biostar3/forum/urls                                          6      0   100%
biostar3/forum/user_views                                  120     46    62%
biostar3/middleware                                         53     21    60%
biostar3/settings/__init__                                   0      0   100%
biostar3/settings/base                                      53      3    94%
biostar3/settings/celeryconfig                               5      0   100%
biostar3/settings/logconf                                   10      5    50%
biostar3/settings/values                                    91      0   100%
biostar3/urls                                                8      0   100%
biostar3/utils/__init__                                      1      0   100%
biostar3/utils/compat                                       20      4    80%
biostar3/utils/email_reply_parser                           72     53    26%
biostar3/utils/flatpage                                     55     55     0%
biostar3/wsgi_default                                        5      5     0%
biostar3/wsgi_whitenoise                                     8      8     0%
manage                                                       6      0   100%
run/__init__                                                 0      0   100%
run/devel                                                    9      0   100%
run/postgres                                                14     14     0%
run/sqlite                                                  11      0   100%
run/travis                                                   1      1     0%
setup                                                        1      1     0%
----------------------------------------------------------------------------
TOTAL                                                     4188   1506    64%

**Comment by scgruber** [comment]
Working on `flatpage.py`

**Comment by scgruber** [comment]
Working on `user_views.py`

**Comment by ialbert** [comment]
Upgrade path discussed here https://github.com/ialbert/biostar-central/issues/400
